


services:


  web-ui:
    build: ./todo-web-ui
    ports:
      - "4200:80"

  
  monolith:
    image: fizlrock/todo/backend
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://database:27017/todolist
    ports:
      - 9090:9090
    depends_on:
      - database
    networks:
      - internal-network

  database:
    image: mongodb/mongodb-community-server
    volumes:
    - mongodb_data:/data/db
    networks:
      - internal-network
    # ports:
    #   - "27017:27017"

  envoy:
    image: envoyproxy/envoy:v1.29.0
    container_name: envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"  # HTTP вход
      - "9901:9901"  # Панель управления Envoy
    networks:
      - internal-network


  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --import-realm
    restart: always
    volumes:
      - ./keycloak_realms:/opt/keycloak/data/import
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  pg_data:
  mongodb_data:
    

networks:
  internal-network:
  keycloak-network:
