


services:
  todo-service:
    image: fizlrock/todo/backend
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://todo-database:27017/todolist
    ports:
      - 9090:9090
    depends_on:
      - todo-database
    networks:
      - todo-network

      
  todo-database:
    image: mongodb/mongodb-community-server
    volumes:
    - mongodb_data:/data/db
    networks:
      - todo-network
    # ports:
    #   - "27017:27017"

  todo-envoy:
    image: envoyproxy/envoy:v1.29.0
    container_name: envoy
    volumes:
      - ./envoy-proxy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"  # HTTP вход
      - "9901:9901"  # Панель управления Envoy
    networks:
      - todo-network
    depends_on:
      - todo-service

      
volumes:
  mongodb_data:

networks:
  todo-network:
