 spring:

   datasource:
     url: jdbc:postgresql://localhost:5432/waterwalk
     username: postgres
     password: admin
     driver-class-name: org.postgresql.Driver

   liquibase:
     # enable: true
     url: jdbc:postgresql://localhost:5432/waterwalk
     user: postgres
     password: admin
     change-log: "classpath:/db/changelog/db.changelog-master.yaml"

 logging:
   level:
     org.springframework.jdbc: TRACE


#spring:
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/waterwalk
#    username: admin
#    password: gracesecret
#    driver-class-name: org.postgresql.Driver
#
#  liquibase:
#    # enable: true
#    url: jdbc:postgresql://localhost:5432/waterwalk
#    user: admin
#    password: gracesecret
#    change-log: "classpath:/db/changelog/db.changelog-master.yaml"
#
#logging:
#  level:
#    org.springframework.jdbc: TRACE
#    org.springframework.data: TRACE
