

grpc:
  server:
    security:
      enabled: false

spring:
  grpc:
    server:
      port: 9090

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

logging:
  level:
    root: info
    dev.fizlrock: trace
